# Generated by Django 6.0.5 on 2026-05-30 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True, verbose_name='日期')),
                ('mode', models.CharField(blank=True, max_length=20, verbose_name='心情')),
                ('energy', models.IntegerField(blank=True, null=True, verbose_name='精力分')),
                ('summary', models.TextField(blank=True, verbose_name='今日总结')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
