# Generated by Django 6.0.5 on 2026-05-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_dailyrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='mode',
            new_name='mood',
        ),
    ]
