# Generated by Django 6.0.5 on 2026-05-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_rename_mode_dailyrecord_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='energy',
            field=models.IntegerField(blank=True, null=True, verbose_name='精力值'),
        ),
    ]
