# Generated by Django 6.0.5 on 2026-05-31 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_alter_dailyrecord_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='daily_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='observations.dailyrecord', verbose_name='所属日期记录'),
        ),
    ]
