# Generated by Django 6.0.5 on 2026-06-02 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_dailyrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='日期'),
        ),
    ]
