# Generated by Django 6.0.5 on 2026-06-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_alter_dailyrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_end',
            field=models.TimeField(blank=True, null=True, verbose_name='计划结束时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_start',
            field=models.TimeField(blank=True, null=True, verbose_name='计划开始时间'),
        ),
    ]
