# Generated by Django 6.0.5 on 2026-06-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_task_completed_at_task_planned_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='是否在首页重点关注'),
        ),
    ]
