# Generated by Django 6.0.5 on 2026-06-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_habit_habitperiod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitperiod',
            old_name='staet_date',
            new_name='start_date',
        ),
    ]
