# Generated by Django 6.0.5 on 2026-06-05 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_rename_staet_date_habitperiod_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='observations.habit', verbose_name='来源习惯'),
        ),
    ]
