# Generated by Django 6.0.5 on 2026-06-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0012_task_source_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否已删除'),
        ),
        migrations.AddField(
            model_name='task',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='是否已取消'),
        ),
    ]
